name: Main Taski Workflow

on:
  push:
    branches:
      main

jobs:
  checkout-and-print-three:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositiry code
        uses: actions/checkout@v3
      - name: Print project three
        uses: tree .

